---
- name: Create Required Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/teslamate"
    - "{{ docker_dir }}/teslamate/grafana"

- name: Copy teslamate.yml to remote host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/tasks/tesla/compose/docker-compose.yaml"
    dest: "{{ docker_dir }}/teslamate/docker-compose.yaml"
    mode: '0644'

- name: Copy TeslaMate .env file to remote host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/tasks/tesla/compose/.env"
    dest: "{{ docker_dir }}/teslamate/.env"
    mode: '0600'

- name: Start TeslaMate stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/teslamate"
    files: docker-compose.yaml
    state: present