---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Update dnf packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
  when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]

- name: Install dnf-utils if on Fedora
  ansible.builtin.package:
    name: dnf-utils
    state: present
  when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]

- name: Check if a reboot is required on Fedora
  ansible.builtin.command: needs-restarting -r
  register: reboot_required
  ignore_errors: true
  changed_when: reboot_required.rc != 0
  when: ansible_distribution in ["Fedora", "CentOS", "RedHat"]

- name: Reboot if required on Fedora
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: ansible_distribution in ["Fedora", "CentOS", "RedHat "] and reboot_required.rc == 1

- name: Check if reboot required on Ubuntu
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Reboot if required on Ubuntu
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: (ansible_distribution in ["Ubuntu", "Debian"]) and reboot_required_file.stat.exists

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present
    extra_args: --break-system-packages