---
- name: Create Required Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/radarr"

- name: Add required permissions to data and docker_apps directories
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ docker_dir }}/radarr"

- name: Create Radarr Container
  community.docker.docker_container:
    name: radarr
    image: linuxserver/radarr:latest
    restart_policy: unless-stopped
    state: started
    ports:
      - 7878:7878
    volumes:
      - "{{ docker_dir }}/radarr:/config"
      - "{{ docker_dir }}/shared:/shared"
      - /etc/localtime:/etc/localtime:ro
      - media_movies:/movies
      - media_downloads:/downloads
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    networks:
      - name: "{{ network_caddy }}"
    labels:
      caddy: "radarr.internal.{{domain}}"
      caddy.reverse_proxy: "{{ '{{upstreams 7878}}' }}"
  